#!/bin/sh
#echo "Content-Type: text/plain\n\n"
echo "Content-Type: text/html\n\n" #TODO whats the content-type for JSON again??
#echo "<span style='color: red'>hello</span> from sh, will pipe using jq soon"
# printenv # will fail as httpd chroot bin/ doesn't contain printenv
#echo "</br>"
#echo "<b>`which date`</b>..."
#echo "<b>`jq --version`...</b>..."
#echo "</br>"
#echo "hello from sh, will pipe using jq soon... `date`"
#echo "</br>"
#echo "<h1>`date`</h1>"
echo "shall not use shell, but statically complied C with pledge to specifcy the syscalls"
echo $HTTP_ENV
echo $SERVER_NAME
echo $SERVER_SOFTWARE
echo $PATH_INFO
echo $REMOTE_USER
echo $CONTENT_TYPE
echo $CONTENT_LENGTH
echo $REMOTE_ADDR
echo $REQUEST_METHOD
echo $HTTP_USER_AGENT
echo $QUERY_STRING
echo $REMOTE_USER
echo $HTTP_REFERER
#echo "</br>"
#echo "We are tryin to make events out of data records; 
#</br> 
#1. collect datasets from datasources
#</br>
#2. extract records from datasets as a generated commands/events
#</br>
#3. use the generated events as an input to datafilters and output as 'smarter' datasets
#</br>
#4. share the produced datasets"
#echo '</br>'
